### ISSUE TITLE
Check for beta-updates

### ISSUE THREAD

**Issue by Clamb94** [Neargye/semver#26]
Hi,
is there an option to check for new beta versions as well?
When comparing `0.10.0-beta.2 > 0.10.0-beta.1`, the result will be _FALSE_.
I'd also like to check if the beta version increased.

Best regards
Axel

**Comment by Naratzul** [comment]
Hi, Axel.

Could you give us a code snippet of your problem? I've just tested the following example.
```
constexpr version v1 = {0, 10, 0, prerelease::beta, 1};
constexpr version v2 = {0, 10, 0, prerelease::beta, 2};
std::cout << (v2 > v1) << std::endl;
```  
The result.
`1`

**Comment by Clamb94** [comment]
I'm very sorry, my mistake. Mixed something up. Works just as expected
