### ISSUE TITLE
Limitation to `std::uint8_t` might yield an overflow for some projects

### ISSUE THREAD

**Issue by daixtrose** [Neargye/semver#31]
Checking the [semver rules](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) I am unsure whether a [limitation to a value range from 0..255](https://github.com/Neargye/semver/blob/master/include/semver.hpp#L273) (i.e. a limitation to `std::uint8_t`) is 

1. required and
1. a wise design decision, especially for [the patch number](https://github.com/Neargye/semver/blob/master/include/semver.hpp#L275)

Could you please explain your design decision?

**Comment by Neargye** [comment]
This limitation will be removed in the new version(0.4.0), there will be full support for semver.

**Comment by Danielmelody** [comment]
Better to provide an template parameter for custom data precision

**Comment by JaiganeshKumaran** [comment]
> This limitation will be removed in the new version(0.4.0), there will be full support for semver.

I reälly need this. Can you do this now?

**Comment by Neargye** [comment]
@JaiganeshKumaran  now it's `std::uint16_t`

**Comment by JaiganeshKumaran** [comment]
Okay but the vcpkg has not been updated yet.

**Comment by JaiganeshKumaran** [comment]
@Neargye

**Comment by daixtrose** [comment]
@JaiganeshKumaran you are aware this is an Open Source project for which you did not pay?
