### ISSUE TITLE
Adding semver to vcpkg

### ISSUE THREAD

**Issue by Vennor** [Neargye/semver#7]
Hi! I created a pull request to the vcpkg repository adding support for your library that you can see here: microsoft/vcpkg#12406. Alas, maintainers requested that the name in vcpkg be changed to something more specific than `semver` which they deemed to generic given the unestabilished status of the library.

Do you have any other preferences or should we go with the proposed `Neargye-semver`?

**Comment by Neargye** [comment]
Hi, yes I think the name `neargye-semver` will be ok.
it seems like a frequent practice like [nlohmann-json](https://github.com/Microsoft/vcpkg/tree/master/ports/nlohmann-json)

**Comment by Vennor** [comment]
Thanks! I updated the merge request.
